# Generated by Django 5.2.1 on 2025-05-20 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_techicon_alter_project_urls'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=100, unique=True)),
                ('count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
