# Generated by Django 5.2 on 2025-05-22 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_pageview'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ml_Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='projects/')),
                ('urls', models.URLField()),
            ],
        ),
    ]
